/**
 * Running tests with CLI
 *  npx playwright test :: runs every test 
 *  npx playwright test --project=<projectName> :: Runs only the specified project
 *  npx playwright show-report :: shows the last report generated by playwright
 * 
 * -----------------------------------
 * 
 * Test annotations
 *  test.skip() :: skips the test during run
 *  test.only() :: runs only the marked tests
 * 
 * -----------------------------------
 * 
 * Timeouts
 *  Global > Test > Action & Navigation & Expect
 *  Global timeout :: limit whole test run
 *  Test Timeout :: limit for single test
 *  Action Timeout :: limit for action command; i.e. .click()
 *  Navigation Timeout :: limit for action command; i.e. page.goto('/')
 *  Expect Timeout :: limit for 'expect' locator assertions
 * 
 * -----------------------------------
 * 
 * Code Generation
 *  Speeds up SDLC
 *  NOTE: Always review generated code for accuracy. There might be a better way than what computer generated
 *  Playwright tools
 *      Pick locator :: Playwright will open the browser and help with the locators for the interacted object
 *      Record new :: creates a new .spec.ts file, creates the test, and allows you to record your test steps
 *      Record at cursor :: starts recording at wherever you had your cursor last i.e. in the middle/end of a test you are writing
 *  AI Tools
 *      VS Code AI Chat Panel
 */

import { expect, test } from '@playwright/test';

test.beforeEach(async ({ page }) => {
    await page.goto('https://playground.bondaracademy.com/');

    // Change theme to dark
    await page.locator('span', { hasText: ' Light' }).click();
    await page.locator('nb-option', { hasText: ' Dark' }).click();

    await page.getByText('Forms').click();
    await page.getByRole('link', { name: 'Form Layouts' }).click();
});

test('Locator Syntax Rules', async ({ page }) => {
    // Find by Tag
    page.locator('input')

    // Find element by ID
    page.locator('#inputEmail1')

    // Find element by Class
    page.locator('.shape-rectangle')

    // Find element by Attribute
    page.locator('[placeholder="Email"]')

    // Find element by full class value
    page.locator('[class="input-full-width size-medium status-basic shape-rectangle nb-transition"]')

    // Find by several selectors
    page.locator('input[placeholder="Email"][nbinput]')

    // Find by xpath (NOT RECOMMENDED)
    page.locator('//*[@id="inputEmail1"]')

    // Find by text (partial match)
    page.locator(':text("Using")')

    // Find by text (exact match)
    page.locator(':text-is("Using the Grid")')
});

test('User-visible locators', async ({ page }) => {
    await page.getByRole('button', { name: 'Sign in' }).first().click();
    await page.getByRole('textbox', { name: 'Email' }).first().fill('test@example.com');

    // The .fill() method will automatically activate and clear the input field before typing, so you don't need to call .click() or .clear() before it
    await page.getByLabel('Email').first().fill('test@test.com');

    await page.getByPlaceholder('Jane Doe').first().fill('Jimothy Bimblesnap');

    await page.getByText('Submit').first().click();

    await page.getByTestId('inputEmail1').fill('testerson@test.com');

    await page.getByTitle('IoT Dashboard').click();
});

test('Locating child elements', async ({ page }) => {
    await page.locator('nb-card').locator('nb-radio-group').locator(':text-is("Option 1")').click();
    await page.locator('nb-card nb-radio-group :text-is("Option 2")').click();

    await page.locator('nb-card').getByRole('button', { name: 'Sign in' }).first().click();

    await page.locator('nb-card').nth(3).getByRole('button').click();
});

test('Locating parent elements', async ({ page }) => {
    await page.locator('nb-card', { hasText: 'Using the Grid' }).getByRole('button').click();
    await page.locator('nb-card', { has: page.locator('#inputEmail1') }).getByRole('button').click();

    await page.locator('nb-card').filter({ hasText: 'Using the Grid' }).getByRole('button').click();

    // Using multiple filters to locate a specific element
    await page.locator('nb-card')
        .filter({ has: page.locator('nb-checkbox') })
        .filter({ hasText: 'Sign in' })
        .getByLabel('Email')
        .fill('test@example.com')

    // Using the locator to find the parent element of a specific text
    await page.getByText('Using the Grid').locator('..').getByRole('button').click();
});

test('Reusing locators', async ({ page }) => {
    // await page.locator('nb-card', { hasText: 'Basic form' }).getByLabel('Email').fill('test@test.com');
    // await page.locator('nb-card', { hasText: 'Basic form' }).getByLabel('Password').fill('password123');
    // await page.locator('nb-card', { hasText: 'Basic form' }).locator('nb-checkbox').click();
    // await page.locator('nb-card', { hasText: 'Basic form' }).getByRole('button').click();

    const basicFormSection = page.locator('nb-card', { hasText: 'Basic form' });
    const emailInputField = basicFormSection.getByLabel('Email');

    await emailInputField.fill('test@test.com');
    await basicFormSection.getByLabel('Password').fill('password123');
    await basicFormSection.locator('nb-checkbox').click();
    await basicFormSection.getByRole('button').click();

    await expect(emailInputField).toHaveValue('test@test.com');
});

test('Extracting text from elements', async ({ page }) => {
    // Extracting text from an element 
    const basicFormSection = page.locator('nb-card', { hasText: 'Basic form' });
    const submitButtonText = await basicFormSection.getByRole('button').textContent();
    expect(submitButtonText).toEqual('Submit');

    // Extract multiple text values 
    const allRadioButtonValues = await page.locator('nb-radio').allTextContents();
    expect(allRadioButtonValues).toContain('Option 1');
    expect(allRadioButtonValues).toEqual(['Option 1', 'Option 2', 'Disabled Option']);

    // Extract input field values
    const emailField = basicFormSection.getByRole('textbox', { name: 'Email' });
    await emailField.fill('jimberly@example.com');
    const emailFieldValue = await emailField.inputValue();
    expect(emailFieldValue).toEqual('jimberly@example.com');

    // Extract attribute values
    const emailPlaceholder = await emailField.getAttribute('placeholder');
    console.log(`Email field placeholder: '${emailPlaceholder}'`);
});

test('Assertions', async ({ page }) => {
    const basicFormSectionButton = page.locator('nb-card', { hasText: 'Basic form' }).getByRole('button');

    // Generic assertions
    const value = 5
    expect(value).toEqual(5);

    const submitButtonText = await basicFormSectionButton.textContent();
    expect(submitButtonText).toEqual('Submit');

    // Locator assertions - has a built-in wait for the element
    await expect(basicFormSectionButton).toHaveText('Submit');

    // Soft assertions - will not fail the test immediately, but will log the failure
    await expect.soft(basicFormSectionButton).toHaveText('Submit');
    await basicFormSectionButton.click();
});
